### ISSUE TITLE
Use littler to install R packages

### ISSUE THREAD

**Issue by abkfenris** [oceanhackweek/jupyter-image#19]
Ahh, we don't have to make our own script. We can add [`littler`](https://github.com/eddelbuettel/littler) via Conda, then:

```
install.R -r https://cloud.r-project.org/ biomod2
installGithub.R BigelowLab/rasf BigelowLab/ohwobpg
```

_Originally posted by @abkfenris in https://github.com/oceanhackweek/jupyter-image/pull/17#issuecomment-672964691_

**Comment by ocefpaf** [comment]
Nice! But we need that in the postBuild anyways, right?

**Comment by abkfenris** [comment]
Ya, we would still need something in postBuild with littler. 

I think the problem that it would help solve is that the current [`Rscript` commands](https://github.com/oceanhackweek/jupyter-image/blob/28d1c7b8e225ef43b2ae48a2c93df4dcd830202d/postBuild#L16-L18) don't appropriately explode when there is an error.

**Comment by ocefpaf** [comment]
I'm almost done with the new image. It will have littler there.
