### ISSUE TITLE
We have an image but master is looking for :latest instead of :master

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/jupyter-image#2]
@emiliom and @salvis2 I guess we need to tweak a name somewhere b/c we got an image built, see https://hub.docker.com/repository/registry-1.docker.io/uwhackweeks/oceanhackweek/tags but the GH actions on master failed looking for a `:latest` tag instead. It is late here and I'll debug this tomorrow morning.

**Comment by emiliom** [comment]
Almost there, thanks!

**Comment by ocefpaf** [comment]
@salvis2 we publish with the `master` tag in

https://github.com/oceanhackweek/jupyter-image/blob/master/.github/workflows/master.yml#L37

and then test with the latest tag in

https://github.com/oceanhackweek/jupyter-image/blob/master/.github/workflows/master.yml#L41

is that correct? Am I missing some DockerHub detail?

I renamed `master` to `latest` just to see if it passes that test. The image looks OK though.

**Comment by ocefpaf** [comment]
Renaming works, see https://github.com/oceanhackweek/jupyter-image/runs/942887544?check_suite_focus=true, but that was not in the original so I'm not 100% sure that is the right thing to do.

**Comment by emiliom** [comment]
Great to see this progress! 

@salvis2: @ocefpaf is tied up today. I'm not sure, but it looked like Filipe would like your input here? Can you help? What I can report is that the OHW image is not visible as an option (or THE option) when logging in to the hub, staging or production (or if it is, it's still labelled as ICESat-2).

In case it's helpful here, I'm pasting what @salvis2 posted a few days ago:

> Actually, someone else can change that if they want. It's pretty simple, since you can just change the .yaml file and push it. GitHub Actions will take over from there and make the hub with the new settings. The [staging config for the image is here](https://github.com/oceanhackweek/ohw-jupyterhub-2020/blob/staging/deployments/ohw-hub/config/staging.yaml#L15-L18)
and [prod is here](https://github.com/oceanhackweek/ohw-jupyterhub-2020/blob/staging/deployments/ohw-hub/config/prod.yaml#L11-L14)

The stage and prod config files are pointing to `uwhackweeks/icesat2:latest`, not `uwhackweeks/oceanhackweek:latest`

**Comment by salvis2** [comment]
> Great to see this progress!
> 
> @salvis2: @ocefpaf is tied up today. I'm not sure, but it looked like Filipe would like your input here? Can you help? What I can report is that the OHW image is not visible as an option (or THE option) when logging in to the hub, staging or production (or if it is, it's still labelled as ICESat-2).

Yeah we were working through some changes to the config and testing the GitHub Actions. It's looking fine, there's just a couple things to add. Since @ocefpaf is busy today, I'll just push to the branch he made and finish it up.

**Comment by salvis2** [comment]
Image is available and launches on both hubs.

**Comment by emiliom** [comment]
Woo-hooo!!! I can confirm it!
