### ISSUE TITLE
OHW 21 environment changes

### ISSUE THREAD

**Issue by abkfenris** [oceanhackweek/jupyter-image#20]
Overall tracking issue for any changes we need to make to our environment for OceanHackWeek 21.

**Comment by MathewBiddle** [comment]
add [ioos-compliance-checker](https://github.com/ioos/compliance-checker)

**Comment by abkfenris** [comment]
- [ ] Keras for R - [Slack message](https://oceanhackweek.slack.com/archives/CVACP79SQ/p1627395793020400)

**Comment by ocefpaf** [comment]
- [ ] r-oce
- [ ] r-gsw

**Comment by emiliom** [comment]
- [ ] [fsspec](https://anaconda.org/conda-forge/fsspec)
- [ ] [s3fs](https://anaconda.org/conda-forge/s3fs) for AWS S3 access

It's possible that these are already being installed as dependencies, though

**Comment by paigem** [comment]
- [ ] xgcm

For Julius

**Comment by jbusecke** [comment]
- [ ] regionmask

Its an optional dependency for `cmip6_preprocessing` but might be helpful for masking out ocean basins.

**Comment by abkfenris** [comment]
Since we're through the OceanHackWeek 2021 looking glass, I'm going to close this issue.
